services:
  - type: web
    name: painter-api
    env: python
    buildCommand: bash render-deploy.sh
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production 