services:
  - type: web
    name: painter
    env: node
    buildCommand: bash ./build.sh
    startCommand: npm install && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0 