services:
  - type: web
    name: painter
    env: node
    buildCommand: chmod +x debug-build.sh && ./debug-build.sh
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0 