services:
  - type: web
    name: painter-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: NODE_ENV
        value: production 