services:
  - type: web
    name: painter
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm install && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0 