services:
  - type: web
    name: painter-client
    env: node
    buildCommand: bash render-deploy.sh
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production 